experiment_name: Exp1
batch_size: 4
max_epochs: 10
model_name: MoCo
embedding_size: 128 #default to 4096
print_model_summary: false
labels_flag: false
loss_name: Contrastive
dataset_size: full
resolution: 224
augmented: false